-- Countries/territories for FoodLife profile country selection.
-- Source: Unicode CLDR territory display names, cs + en.
-- Import is safe to run repeatedly.

CREATE TABLE IF NOT EXISTS `countries` (
  `code` char(2) NOT NULL,
  `name_cs` varchar(120) NOT NULL,
  `name_en` varchar(120) NOT NULL,
  PRIMARY KEY (`code`),
  KEY `idx_countries_name_cs` (`name_cs`),
  KEY `idx_countries_name_en` (`name_en`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_czech_ci;

INSERT INTO `countries` (`code`, `name_cs`, `name_en`) VALUES
('AF', 'Afghánistán', 'Afghanistan'),
('AX', 'Ålandy', 'Åland Islands'),
('AL', 'Albánie', 'Albania'),
('DZ', 'Alžírsko', 'Algeria'),
('AS', 'Americká Samoa', 'American Samoa'),
('VI', 'Americké Panenské ostrovy', 'U.S. Virgin Islands'),
('AD', 'Andorra', 'Andorra'),
('AO', 'Angola', 'Angola'),
('AI', 'Anguilla', 'Anguilla'),
('AQ', 'Antarktida', 'Antarctica'),
('AG', 'Antigua a Barbuda', 'Antigua & Barbuda'),
('AR', 'Argentina', 'Argentina'),
('AM', 'Arménie', 'Armenia'),
('AW', 'Aruba', 'Aruba'),
('AC', 'Ascension', 'Ascension Island'),
('AU', 'Austrálie', 'Australia'),
('AZ', 'Ázerbájdžán', 'Azerbaijan'),
('BS', 'Bahamy', 'Bahamas'),
('BH', 'Bahrajn', 'Bahrain'),
('BD', 'Bangladéš', 'Bangladesh'),
('BB', 'Barbados', 'Barbados'),
('BE', 'Belgie', 'Belgium'),
('BZ', 'Belize', 'Belize'),
('BY', 'Bělorusko', 'Belarus'),
('BJ', 'Benin', 'Benin'),
('BM', 'Bermudy', 'Bermuda'),
('BT', 'Bhútán', 'Bhutan'),
('BO', 'Bolívie', 'Bolivia'),
('BA', 'Bosna a Hercegovina', 'Bosnia & Herzegovina'),
('BW', 'Botswana', 'Botswana'),
('BV', 'Bouvetův ostrov', 'Bouvet Island'),
('BR', 'Brazílie', 'Brazil'),
('IO', 'Britské indickooceánské území', 'British Indian Ocean Territory'),
('VG', 'Britské Panenské ostrovy', 'British Virgin Islands'),
('BN', 'Brunej', 'Brunei'),
('BG', 'Bulharsko', 'Bulgaria'),
('BF', 'Burkina Faso', 'Burkina Faso'),
('BI', 'Burundi', 'Burundi'),
('EA', 'Ceuta a Melilla', 'Ceuta & Melilla'),
('CP', 'Clippertonův ostrov', 'Clipperton Island'),
('CK', 'Cookovy ostrovy', 'Cook Islands'),
('CW', 'Curaçao', 'Curaçao'),
('TD', 'Čad', 'Chad'),
('ME', 'Černá Hora', 'Montenegro'),
('CZ', 'Česko', 'Czechia'),
('CN', 'Čína', 'China'),
('DK', 'Dánsko', 'Denmark'),
('DG', 'Diego García', 'Diego Garcia'),
('DM', 'Dominika', 'Dominica'),
('DO', 'Dominikánská republika', 'Dominican Republic'),
('DJ', 'Džibutsko', 'Djibouti'),
('EG', 'Egypt', 'Egypt'),
('EC', 'Ekvádor', 'Ecuador'),
('ER', 'Eritrea', 'Eritrea'),
('EE', 'Estonsko', 'Estonia'),
('SZ', 'Eswatini', 'Eswatini'),
('ET', 'Etiopie', 'Ethiopia'),
('FO', 'Faerské ostrovy', 'Faroe Islands'),
('FK', 'Falklandské ostrovy', 'Falkland Islands'),
('FJ', 'Fidži', 'Fiji'),
('PH', 'Filipíny', 'Philippines'),
('FI', 'Finsko', 'Finland'),
('FR', 'Francie', 'France'),
('GF', 'Francouzská Guyana', 'French Guiana'),
('TF', 'Francouzská jižní území', 'French Southern Territories'),
('PF', 'Francouzská Polynésie', 'French Polynesia'),
('GA', 'Gabon', 'Gabon'),
('GM', 'Gambie', 'Gambia'),
('GH', 'Ghana', 'Ghana'),
('GI', 'Gibraltar', 'Gibraltar'),
('GD', 'Grenada', 'Grenada'),
('GL', 'Grónsko', 'Greenland'),
('GE', 'Gruzie', 'Georgia'),
('GP', 'Guadeloupe', 'Guadeloupe'),
('GU', 'Guam', 'Guam'),
('GT', 'Guatemala', 'Guatemala'),
('GG', 'Guernsey', 'Guernsey'),
('GN', 'Guinea', 'Guinea'),
('GW', 'Guinea-Bissau', 'Guinea-Bissau'),
('GY', 'Guyana', 'Guyana'),
('HT', 'Haiti', 'Haiti'),
('HM', 'Heardův ostrov a McDonaldovy ostrovy', 'Heard & McDonald Islands'),
('HN', 'Honduras', 'Honduras'),
('HK', 'Hongkong – ZAO Číny', 'Hong Kong SAR China'),
('CL', 'Chile', 'Chile'),
('HR', 'Chorvatsko', 'Croatia'),
('IN', 'Indie', 'India'),
('ID', 'Indonésie', 'Indonesia'),
('IQ', 'Irák', 'Iraq'),
('IR', 'Írán', 'Iran'),
('IE', 'Irsko', 'Ireland'),
('IS', 'Island', 'Iceland'),
('IT', 'Itálie', 'Italy'),
('IL', 'Izrael', 'Israel'),
('JM', 'Jamajka', 'Jamaica'),
('JP', 'Japonsko', 'Japan'),
('YE', 'Jemen', 'Yemen'),
('JE', 'Jersey', 'Jersey'),
('ZA', 'Jihoafrická republika', 'South Africa'),
('GS', 'Jižní Georgie a Jižní Sandwichovy ostrovy', 'South Georgia & South Sandwich Islands'),
('KR', 'Jižní Korea', 'South Korea'),
('SS', 'Jižní Súdán', 'South Sudan'),
('JO', 'Jordánsko', 'Jordan'),
('KY', 'Kajmanské ostrovy', 'Cayman Islands'),
('KH', 'Kambodža', 'Cambodia'),
('CM', 'Kamerun', 'Cameroon'),
('CA', 'Kanada', 'Canada'),
('IC', 'Kanárské ostrovy', 'Canary Islands'),
('CV', 'Kapverdy', 'Cape Verde'),
('BQ', 'Karibské Nizozemsko', 'Caribbean Netherlands'),
('QA', 'Katar', 'Qatar'),
('KZ', 'Kazachstán', 'Kazakhstan'),
('KE', 'Keňa', 'Kenya'),
('KI', 'Kiribati', 'Kiribati'),
('CC', 'Kokosové ostrovy', 'Cocos (Keeling) Islands'),
('CO', 'Kolumbie', 'Colombia'),
('KM', 'Komory', 'Comoros'),
('CG', 'Kongo – Brazzaville', 'Congo - Brazzaville'),
('CD', 'Kongo – Kinshasa', 'Congo - Kinshasa'),
('XK', 'Kosovo', 'Kosovo'),
('CR', 'Kostarika', 'Costa Rica'),
('CU', 'Kuba', 'Cuba'),
('KW', 'Kuvajt', 'Kuwait'),
('CY', 'Kypr', 'Cyprus'),
('KG', 'Kyrgyzstán', 'Kyrgyzstan'),
('LA', 'Laos', 'Laos'),
('LS', 'Lesotho', 'Lesotho'),
('LB', 'Libanon', 'Lebanon'),
('LR', 'Libérie', 'Liberia'),
('LY', 'Libye', 'Libya'),
('LI', 'Lichtenštejnsko', 'Liechtenstein'),
('LT', 'Litva', 'Lithuania'),
('LV', 'Lotyšsko', 'Latvia'),
('LU', 'Lucembursko', 'Luxembourg'),
('MO', 'Macao – ZAO Číny', 'Macao SAR China'),
('MG', 'Madagaskar', 'Madagascar'),
('HU', 'Maďarsko', 'Hungary'),
('MY', 'Malajsie', 'Malaysia'),
('MW', 'Malawi', 'Malawi'),
('MV', 'Maledivy', 'Maldives'),
('ML', 'Mali', 'Mali'),
('MT', 'Malta', 'Malta'),
('MA', 'Maroko', 'Morocco'),
('MH', 'Marshallovy ostrovy', 'Marshall Islands'),
('MQ', 'Martinik', 'Martinique'),
('MU', 'Mauricius', 'Mauritius'),
('MR', 'Mauritánie', 'Mauritania'),
('YT', 'Mayotte', 'Mayotte'),
('UM', 'Menší odlehlé ostrovy USA', 'U.S. Outlying Islands'),
('MX', 'Mexiko', 'Mexico'),
('FM', 'Mikronésie', 'Micronesia'),
('MD', 'Moldavsko', 'Moldova'),
('MC', 'Monako', 'Monaco'),
('MN', 'Mongolsko', 'Mongolia'),
('MS', 'Montserrat', 'Montserrat'),
('MZ', 'Mosambik', 'Mozambique'),
('MM', 'Myanmar (Barma)', 'Myanmar (Burma)'),
('NA', 'Namibie', 'Namibia'),
('NR', 'Nauru', 'Nauru'),
('DE', 'Německo', 'Germany'),
('NP', 'Nepál', 'Nepal'),
('NE', 'Niger', 'Niger'),
('NG', 'Nigérie', 'Nigeria'),
('NI', 'Nikaragua', 'Nicaragua'),
('NU', 'Niue', 'Niue'),
('NL', 'Nizozemsko', 'Netherlands'),
('NF', 'Norfolk', 'Norfolk Island'),
('NO', 'Norsko', 'Norway'),
('NC', 'Nová Kaledonie', 'New Caledonia'),
('NZ', 'Nový Zéland', 'New Zealand'),
('OM', 'Omán', 'Oman'),
('IM', 'Ostrov Man', 'Isle of Man'),
('PK', 'Pákistán', 'Pakistan'),
('PW', 'Palau', 'Palau'),
('PS', 'Palestinská území', 'Palestinian Territories'),
('PA', 'Panama', 'Panama'),
('PG', 'Papua-Nová Guinea', 'Papua New Guinea'),
('PY', 'Paraguay', 'Paraguay'),
('PE', 'Peru', 'Peru'),
('PN', 'Pitcairnovy ostrovy', 'Pitcairn Islands'),
('CI', 'Pobřeží slonoviny', 'Côte d’Ivoire'),
('PL', 'Polsko', 'Poland'),
('PR', 'Portoriko', 'Puerto Rico'),
('PT', 'Portugalsko', 'Portugal'),
('AT', 'Rakousko', 'Austria'),
('RE', 'Réunion', 'Réunion'),
('GQ', 'Rovníková Guinea', 'Equatorial Guinea'),
('RO', 'Rumunsko', 'Romania'),
('RU', 'Rusko', 'Russia'),
('RW', 'Rwanda', 'Rwanda'),
('GR', 'Řecko', 'Greece'),
('PM', 'Saint-Pierre a Miquelon', 'St. Pierre & Miquelon'),
('SV', 'Salvador', 'El Salvador'),
('WS', 'Samoa', 'Samoa'),
('SM', 'San Marino', 'San Marino'),
('CQ', 'Sark', 'Sark'),
('SA', 'Saúdská Arábie', 'Saudi Arabia'),
('SN', 'Senegal', 'Senegal'),
('KP', 'Severní Korea', 'North Korea'),
('MK', 'Severní Makedonie', 'North Macedonia'),
('MP', 'Severní Mariany', 'Northern Mariana Islands'),
('SC', 'Seychely', 'Seychelles'),
('SL', 'Sierra Leone', 'Sierra Leone'),
('SG', 'Singapur', 'Singapore'),
('SK', 'Slovensko', 'Slovakia'),
('SI', 'Slovinsko', 'Slovenia'),
('SO', 'Somálsko', 'Somalia'),
('AE', 'Spojené arabské emiráty', 'United Arab Emirates'),
('GB', 'Spojené království', 'United Kingdom'),
('US', 'Spojené státy', 'United States'),
('RS', 'Srbsko', 'Serbia'),
('LK', 'Srí Lanka', 'Sri Lanka'),
('CF', 'Středoafrická republika', 'Central African Republic'),
('SD', 'Súdán', 'Sudan'),
('SR', 'Surinam', 'Suriname'),
('SH', 'Svatá Helena', 'St. Helena'),
('LC', 'Svatá Lucie', 'St. Lucia'),
('BL', 'Svatý Bartoloměj', 'St. Barthélemy'),
('KN', 'Svatý Kryštof a Nevis', 'St. Kitts & Nevis'),
('MF', 'Svatý Martin (Francie)', 'St. Martin'),
('SX', 'Svatý Martin (Nizozemsko)', 'Sint Maarten'),
('ST', 'Svatý Tomáš a Princův ostrov', 'São Tomé & Príncipe'),
('VC', 'Svatý Vincenc a Grenadiny', 'St. Vincent & Grenadines'),
('SY', 'Sýrie', 'Syria'),
('SB', 'Šalamounovy ostrovy', 'Solomon Islands'),
('ES', 'Španělsko', 'Spain'),
('SJ', 'Špicberky a Jan Mayen', 'Svalbard & Jan Mayen'),
('SE', 'Švédsko', 'Sweden'),
('CH', 'Švýcarsko', 'Switzerland'),
('TJ', 'Tádžikistán', 'Tajikistan'),
('TZ', 'Tanzanie', 'Tanzania'),
('TH', 'Thajsko', 'Thailand'),
('TW', 'Tchaj-wan', 'Taiwan'),
('TG', 'Togo', 'Togo'),
('TK', 'Tokelau', 'Tokelau'),
('TO', 'Tonga', 'Tonga'),
('TT', 'Trinidad a Tobago', 'Trinidad & Tobago'),
('TA', 'Tristan da Cunha', 'Tristan da Cunha'),
('TN', 'Tunisko', 'Tunisia'),
('TR', 'Turecko', 'Türkiye'),
('TM', 'Turkmenistán', 'Turkmenistan'),
('TC', 'Turks a Caicos', 'Turks & Caicos Islands'),
('TV', 'Tuvalu', 'Tuvalu'),
('UG', 'Uganda', 'Uganda'),
('UA', 'Ukrajina', 'Ukraine'),
('UY', 'Uruguay', 'Uruguay'),
('UZ', 'Uzbekistán', 'Uzbekistan'),
('CX', 'Vánoční ostrov', 'Christmas Island'),
('VU', 'Vanuatu', 'Vanuatu'),
('VA', 'Vatikán', 'Vatican City'),
('VE', 'Venezuela', 'Venezuela'),
('VN', 'Vietnam', 'Vietnam'),
('TL', 'Východní Timor', 'Timor-Leste'),
('WF', 'Wallis a Futuna', 'Wallis & Futuna'),
('ZM', 'Zambie', 'Zambia'),
('EH', 'Západní Sahara', 'Western Sahara'),
('ZW', 'Zimbabwe', 'Zimbabwe')
ON DUPLICATE KEY UPDATE
  `name_cs` = VALUES(`name_cs`),
  `name_en` = VALUES(`name_en`);

ALTER TABLE `user_profiles`
  ADD COLUMN IF NOT EXISTS `country_code` char(2) DEFAULT NULL AFTER `gender`;
